<?php

$SELECT = '<select name="idi_nivel_conhecimento">';

echo '<div class="topnav">';
echo '<select class="menu">';
echo '<option value="index.php">Home</option>';
echo '<option value="registro.php">Registrar</option>';
echo '<option value="login.php">Entrar</option>';
echo '<option value="logoff.php">Sair</option>';
echo '<option value="../controller/pessoa.php?acao=carregar">Agenda - Contatos</option>';
echo '<option value="../view/curso_lista.php">Agenda - Recados</option>';
echo '<option value="../view/certificacao_lista.php">Agenda - Eventos</option>';
echo '<option value="../view/experiencia_profissional_lista.php">Agenda - Tipo de Eventos</option>';
echo '<option value="../view/objetivo_profissional_lista.php">Financeiro - Caixa</option>';
echo '<option value="../view/idioma_lista.php">Financeiro - Controle de Cheques</option>';
echo '<option value="../view/habilidade_lista.php">Financeiro - Contas a Pagar</option>';
echo '<option value="../view/vagas.php">Financeiro - Contas a Receber</option>';
echo '<option value="../view/curriculo.php">Controle de Documentos</option>';
echo '<option value="../view/curriculo.php">Tipo de Documentos</option>';
echo '<option value="../view/curriculo.php">Vendas - Produtos</option>';
echo '<option value="../view/publica_vaga_lista.php">Vendas - Seriços</option>';
echo '<option value="../view/curriculo.php">Bancos</option>';
echo '<option value="../view/curriculo.php">Cartórios</option>';
echo '<option value="../view/curriculo.php">Centro de Custos</option>';
echo '<option value="../view/curriculo.php">Clientes</option>';
echo '<option value="../view/curriculo.php">Contadores</option>';
echo '<option value="../view/curriculo.php">Empresas</option>';
echo '<option value="../view/curriculo.php">Fornecedores</option>';
echo '<option value="../view/curriculo.php">Produtos</option>';
echo '<option value="../view/curriculo.php">Produtos - Categoria</option>';
echo '<option value="../view/curriculo.php">Produtos - Marca</option>';
echo '<option value="../view/curriculo.php">Produtos - Unidade</option>';
echo '<option value="../view/curriculo.php">Seguradoras</option>';
echo '<option value="../view/curriculo.php">Serviços</option>';
echo '<option value="../view/curriculo.php">Sindicatos</option>';
echo '<option value="../view/curriculo.php">Veículos - Marca</option>';
echo '<option value="../view/curriculo.php">Veículos - Modelo</option>';
echo '<option value="../view/curriculo.php">Veículos - Pedido de Placas</option>';
echo '<option value="../view/curriculo.php">Veículos - Seguro</option>';
echo $SELECT_ . $TD_ . $TR_;
echo '</div>';