<?php
echo '<div class="topnav">';
echo '<a href="index.php">Home</a>';
echo '<a href="registro.php">Registrar</a>';
echo '<a href="login.php">Entrar</a>';
echo '<a href="logoff.php">Sair</a>';
echo '<a href="../controller/pessoa.php?acao=carregar">Contatos</a>';
echo '<a href="../view/curso_lista.php">Recados</a>';
echo '<a href="../view/certificacao_lista.php">Eventos</a>';
echo '<a href="../view/experiencia_profissional_lista.php">Tipo de Eventos</a>';
echo '<a href="../view/objetivo_profissional_lista.php">Caixa</a>';
echo '<a href="../view/idioma_lista.php">Controle de Cheques</a>';
echo '<a href="../view/habilidade_lista.php">Contas a Pagar</a>';
echo '<a href="../view/vagas.php">Contas a Receber</a>';
echo '<a href="../view/curriculo.php">Controle de Documentos</a>';
echo '<a href="../view/curriculo.php">Tipo de Documentos</a>';
echo '<a href="../view/curriculo.php">Vendas de Produtos</a>';
echo '<a href="../view/publica_vaga_lista.php">Vendas de Seriços</a>';
echo '<a href="../view/curriculo.php">Bancos</a>';
echo '<a href="../view/curriculo.php">Cartórios</a>';
echo '<a href="../view/curriculo.php">Centro de Custos</a>';
echo '<a href="../view/curriculo.php">Clientes</a>';
echo '<a href="../view/curriculo.php">Contadores</a>';
echo '<a href="../view/curriculo.php">Empresas</a>';
echo '<a href="../view/curriculo.php">Fornecedores</a>';
echo '<a href="../view/curriculo.php">Produtos</a>';
echo '<a href="../view/curriculo.php">Categoria de Produtos</a>';
echo '<a href="../view/curriculo.php">Marca de Produtos</a>';
echo '<a href="../view/curriculo.php">Unidade de Produtos</a>';
echo '<a href="../view/curriculo.php">Seguradoras</a>';
echo '<a href="../view/curriculo.php">Serviços</a>';
echo '<a href="../view/curriculo.php">Sindicatos</a>';
echo '<a href="../view/curriculo.php">Marca de Veículos</a>';
echo '<a href="../view/curriculo.php">Modelo de Veículos</a>';
echo '<a href="../view/curriculo.php">Pedido de Placas</a>';
echo '<a href="../view/curriculo.php">Seguro de Veículos</a>';
echo '</div>';