<?php
echo '<div class="linha">';
echo '<div class="coluna esquerda">';
echo '<a href="index.php">Home</a><br>';
echo '<a href="registro.php">Registrar</a><br>';
echo '<a href="login.php">Entrar</a><br>';
echo '<a href="logoff.php">Sair</a><br>-<br>';
echo '<a href="../controller/pessoa.php?acao=carregar">Contatos</a><br>';
echo '<a href="../view/curso_lista.php">Recados</a><br>';
echo '<a href="../view/certificacao_lista.php">Eventos</a><br>';
echo '<a href="../view/experiencia_profissional_lista.php">Tipo de Eventos</a><br>-<br>';
echo '<a href="../view/objetivo_profissional_lista.php">Caixa</a><br>';
echo '<a href="../view/idioma_lista.php">Controle de Cheques</a><br>';
echo '<a href="../view/habilidade_lista.php">Contas a Pagar</a><br>';
echo '<a href="../view/vagas.php">Contas a Receber</a><br>-<br>';
echo '<a href="../view/curriculo.php">Controle de Documentos</a><br>';
echo '<a href="../view/curriculo.php">Tipo de Documentos</a><br>-<br>';
echo '<a href="../view/curriculo.php">Vendas de Produtos</a><br>';
echo '<a href="../view/publica_vaga_lista.php">Vendas de Seriços</a><br>-<br>';
echo '<a href="../view/curriculo.php">Bancos</a><br>';
echo '<a href="../view/curriculo.php">Cartórios</a><br>';
echo '<a href="../view/curriculo.php">Centro de Custos</a><br>';
echo '<a href="../view/curriculo.php">Clientes</a><br>';
echo '<a href="../view/curriculo.php">Contadores</a><br>';
echo '<a href="../view/curriculo.php">Empresas</a><br>';
echo '<a href="../view/curriculo.php">Fornecedores</a><br>-<br>';
echo '<a href="../view/curriculo.php">Produtos</a><br>';
echo '<a href="../view/curriculo.php">Categoria de Produtos</a><br>';
echo '<a href="../view/curriculo.php">Marca de Produtos</a><br>';
echo '<a href="../view/curriculo.php">Unidades de Produtos</a><br>-<br>';
echo '<a href="../view/curriculo.php">Seguradoras</a><br>';
echo '<a href="../view/curriculo.php">Serviços</a><br>';
echo '<a href="../view/curriculo.php">Sindicatos</a><br>-<br>';
echo '<a href="../view/curriculo.php">Marca de Veículos</a><br>';
echo '<a href="../view/curriculo.php">Modelo de Veículos</a><br>';
echo '<a href="../view/curriculo.php">Pedidos de Placas</a><br>-<br>';
echo '<a href="../view/curriculo.php">Seguro de Veículos</a><br>';
echo '</div>';